client_secret: UsC5sNDciSaNggxJdB3EGSGYS242VT7q
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: true
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: true
ip_report_period: 1800
report_delay: 4
server: nzku.fortymenty.eu.org:443
skip_connection_count: true
skip_procs_count: true
temperature: false
tls: true
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: 84fb71cf-4f62-4096-9640-8caa07de8922
